version: '3.8'

services:
  app:
    image: beatboxbox:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: beatboxbox
    depends_on:
      - db
    networks:
      - beatboxbox-backend-network

  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: beatboxbox
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - beatboxbox-backend-network

volumes:
  postgres_data:

networks:
  beatboxbox-backend-network:
    driver: bridge
