services:
  beatboxbox-server:
    image: beatboxbox:latest
    ports:
      - "3000:3000"
    depends_on:
      - beatboxbox-db
    networks:
      - beatboxbox-backend-network

  beatboxbox-db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - beatboxbox-backend-network

volumes:
  postgres_data:

networks:
  beatboxbox-backend-network:
    driver: bridge
