name: cleanup-old-workflows
on:
  push:
  schedule:
      - cron: '0 0 * * 0'
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup old workflows
        run: |
          OLD_RUNS_IDS=$(curl -fL -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/BoxBoxJason/BeatBoxBox/actions/runs | jq -r '.workflow_runs | group_by(.name) | map(sort_by(.created_at) | .[0:-1]) | flatten | .[].id')
          for RUN_ID in $OLD_RUNS_IDS; do
              echo "Deleting run $RUN_ID"
              curl -fsL -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/BoxBoxJason/BeatBoxBox/actions/runs/$RUN_ID
          done

