name: go-test
on: [push, pull_request]
jobs:
  gotestsum:
    runs-on: ubuntu-latest
    services:
      beatboxbox-db:
        image: postgres:16.3-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: beatboxbox
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest && go mod tidy

      - name: Setup fake TLS certificates
        run: |
          sudo apt-get install -y openssl
          mkdir -p ./secret
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./secret/key.pem -out ./secret/cert.pem -subj "/C=US/ST=California/L=San Francisco/O=Your Company Name/OU=Org/CN=localhost"
      
      - name: Run tests
        run: |
          export DB_HOST=localhost
          export DB_PORT=5432
          export DB_USER=admin
          export DB_PASSWORD=admin
          export DB_NAME=beatboxbox
          export DB_SSLMODE=disable
          export JWT_SECRET=secret
          gotestsum --junitfile gotestsum.xml ./...

      - name: Show test results
        run: cat gotestsum.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: gotestsum-results
          path: gotestsum.xml
