name: vue-lint
on: [push, pull_request]
jobs:
  vue-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run ESLint
        run: cd frontend && npm install --legacy-peer-deps && npx eslint . > eslint-report.txt
      
      - name: Display ESLint report
        run: cat frontend/eslint-report.txt

      - name: Upload ESLint report
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: frontend/eslint-report.txt
